### ISSUE TITLE
[Home Page] Card Block Variants

### ISSUE THREAD

**Issue by kmurugulla** [hlxsites/zemax#10]
There are multiple card variants 

Note - Please feel free to create sub items of this issue and Update Block [Library](https://main--zemax--hlxsites.hlx.page/block-library/how-to-block-library)

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/7944122/227591177-6979a921-0198-4306-b615-e24ede1b8f0b.png">

![Screenshot 2023-04-06 at 10 11 06 AM](https://user-images.githubusercontent.com/2826121/230448752-f336d741-e5e8-4ccd-8ecc-21a8be1182bd.png)

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/7944122/227592297-c40c5896-c0a1-4b64-9716-0f366d5c29c8.png">

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/7944122/227592555-5b4d7c67-e518-405a-aaf8-c17235c18094.png">

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/7944122/227592677-ee1c41fb-ea92-48fb-80c4-b595ded88eda.png">

There are multiple variants of Card Blocks on the home page 

- [x] Product
- [x] Customer Success Story
- [ ] Training
- [ ] Events
- [ ] News

the variant factors are

- [ ] Width
- [ ] Color
- [ ] Image / no - image
- [ ] Image location
- [ ] Card Label

**Comment by FrancoisZhang** [comment]
sub task created: https://github.com/hlxsites/zemax/issues/36

**Comment by FrancoisZhang** [comment]
sub task created for Customer Success Story: https://github.com/hlxsites/zemax/issues/39

**Comment by FrancoisZhang** [comment]
sub task created for zemax training: https://github.com/hlxsites/zemax/issues/44

**Comment by FrancoisZhang** [comment]
https://github.com/hlxsites/zemax/pull/50
