### ISSUE TITLE
wrap image with link 

### ISSUE THREAD

**Issue by kmurugulla** [hlxsites/zemax#111]
In Office 365 , insert link for images does not work as in Google docs. So when there is an image followed by a link in the document present , create autoblock to wrap the image into hyper link , clicking on which open the linked page in the same window

Sample page - https://main--zemax--hlxsites.hlx.page/blogs/news/20-year-optics-veteran-talks-product-development-cycles-productivity-hacks-and-the-future

**Comment by MITCHYUGAN** [comment]
Hello, Can I work on this

**Comment by kunwarsaluja** [comment]
This was completed as part of cards block
