### ISSUE TITLE
[Bug] - Tabcordion adjustments

### ISSUE THREAD

**Issue by kunwarsaluja** [hlxsites/zemax#112]
Tabcordion bug fixes 

- make the code and anchors resistant towards anchor links for direct consumption. See [example](https://main--zemax--hlxsites.hlx.page/pages/applications#imaging%20optics)
- alignment of the tabs should be similar to the live site
- in Mobile view, accordion show/hide transition is missing

**Comment by FrancoisZhang** [comment]
in the end, the fixing includes:

- Desktop view: Tab list header layout change
- Desktop view: Fixed switch tab should not scroll by anchor by remove the anchor usage, the proper tab is selected properly if such anchor exists in URL
- Mobile View: the opened accordion can be closed by click the opened one
- Mobile View: icon for opened & closed accordion should be different, and selected tab should be highlighted with orange color.
- Mobile View: add animation when open the accordion
- Refine the responsive width change handler

**Comment by FrancoisZhang** [comment]
Done in PR: https://github.com/hlxsites/zemax/pull/160
