### ISSUE TITLE
[Product Landing Page] Carousel

### ISSUE THREAD

**Issue by kmurugulla** [hlxsites/zemax#15]
The carousel with card is available on product landing pages 

- https://www.zemax.com/pages/opticstudio

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/7944122/227724840-bb8d94ab-4b6d-4f97-8c9a-527d01ce395a.png">

- https://www.zemax.com/pages/opticstudio-star-module

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/7944122/227724945-6ab1b8fb-cf8c-451e-807d-a3f2055ef5ec.png">

- https://www.zemax.com/pages/opticsbuilder

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/7944122/227725025-f7dc80d6-0067-402b-b809-9fe8095f92ae.png">

**Comment by FrancoisZhang** [comment]
close this as duplicated with https://github.com/hlxsites/zemax/issues/77
