### ISSUE TITLE
Profile page: header not loaded for 8+ seconds

### ISSUE THREAD

**Issue by synox** [hlxsites/zemax#165]
It seems like something in the profile page blocks the main thread, so therefore the header does not render. 

Instead the profile page block should return the control of the main thread as soon as the first things are rendered. 

https://github.com/hlxsites/zemax/assets/2250964/2509145d-ebf2-49d9-a2dc-8d04ad5d96ab

cc: @shehjadkhan-ansys

**Comment by agangam** [comment]
Our current loading process for /pages/profiles loads all user-* first then the header. When the user is not logged in, this causes delay in loading the pages. We should make these load after header is loaded.

<img width="1522" alt="image" src="https://github.com/hlxsites/zemax/assets/109620050/938b659c-06bb-4149-b734-4b10005e4f18">

**Comment by shehjadkhan-ansys** [comment]
Correct most of the backend API we are interacting with are slow, we need to add loading user experience and lazy load them.
I plan to do this once we are done with the core functionality. Can we not do these changes till then. Thank you

**Comment by synox** [comment]
Also fix for search-results page
