### ISSUE TITLE
Use a metadata field to secure pages in the list

### ISSUE THREAD

**Issue by agangam** [hlxsites/zemax#170]
My suggestion for this implementation is we add page level metadata field called 'Gated' true or false on basis of that if the user is not logged in we redirect them to Auth0 login page. There are other pages like software download page which are not under directly profile page but are protected by login. For example open this page in incognito window https://www.zemax.com/pages/ansys-ob-downloads you will see that the user if not logged get redirected to the Auth0 login. Also might be a good idea to supplement this metadata field with some regex configuration so for example any page starting with /pages/profiles/* should be protected and thus we don't have to depend on authoring configuration for behavior to be imposed.

**Comment by synox** [comment]
I would call it `requireAuthentication` or similar. 
Not sure we need the regexp, we can just add it to the dozen pages in the docs metadata.

**Comment by agangam** [comment]
![image](https://github.com/hlxsites/zemax/assets/109620050/44bc013d-90e3-4059-a829-8f2b898c5a20)
