### ISSUE TITLE
CSS home page

### ISSUE THREAD

**Issue by Anthony-Hopkins-star** [hlxsites/zemax#190]

**Comment by Anthony-Hopkins-star** [comment]
![image](https://github.com/hlxsites/zemax/assets/135161268/277dc92f-816f-48eb-b7a5-151bade59611)
1. Reduce the height of the top nav to match the original design on zemax.com
2. Reduce the size of the font and make sure it is centered to match the design of zemax.com
3. Reduce the spacing between the 2 lines within title to match the design on zemax.com

![image](https://github.com/hlxsites/zemax/assets/135161268/f9c24f70-5c5b-4f6e-a7c7-0a74e1ea8bd5)
4. "Trusted by" needs to be a smaller font to match the design of zemax.com
5. Reduce the width and make sure that the text appears to be on 2 lines as displayed on zemax.com. Also make sure that the spacing of the title and text is reduced to match the zemax.com design
6. Title should be slightly smaller in size as well as closer to the boxes below. Make sure the boxes below are centered just like they are within the original zemax.com design

![image](https://github.com/hlxsites/zemax/assets/135161268/4aa43f05-7489-4e51-8e92-db1140ff193c)

7. The background color of this section should be the light gray, as displayed within the original zemax.com design.
8. Title should be centered and closer to the boxes below, as displayed within the original zemax.com design.
9. The width of the box is too long and the height of the box is too short. The description text within the box needs to be bigger. The "Learn more" button needs to be in bold. All in order to match the original zemax.com design.
10. The OpticStudio Logo should be smaller. The text underneath the logo should be bigger. The description text should be larger. The "Learn more" link should be in bold. All in order to match the original zemax.com design.
11.  Reduce the spacing between the 2 other boxes below. All in order to match the original zemax.com design.

![image](https://github.com/hlxsites/zemax/assets/135161268/89eabdb3-c35c-4834-bab4-2c46e7a0a398)
12. The title should be centered and smaller in font.  All in order to match the original zemax.com design.

![image](https://github.com/hlxsites/zemax/assets/135161268/2346b098-e9ef-4065-bcbe-dd730e8222ce)
13. "Training" Title needs to be centered. 

![image](https://github.com/hlxsites/zemax/assets/135161268/f4489c9f-12f2-4fe0-9ff5-7b209a5fc356)
14. The title should be centered and the color grey

![image](https://github.com/hlxsites/zemax/assets/135161268/d6e5a1ea-1043-49d9-8b3c-0362f9b6bcea)
15. "Featured News" needs to be smaller and closer to the boxes below. The "View all"  button needs to be closer to the boxes above. All in order to match the original zemax.com design.

**Comment by Anthony-Hopkins-star** [comment]
![image](https://github.com/hlxsites/zemax/assets/135161268/c9fc5e8b-7362-4a22-b5a6-984ee82a7b66)
The following titles need to have padding so they are not pressed against the left side of the screen (mobile)
- Trusted by
- Harness the power of Zemax optics software
- Customer success stories (this should be centered anyway)
- Whats new at Zemax? (this should be centered anyway)
-  Featured Event
- Featured News

**Comment by kmurugulla** [comment]
Please work on tablet and mobile renditions for the same issues.
