### ISSUE TITLE
Imaging Optics CSS

### ISSUE THREAD

**Issue by Anthony-Hopkins-star** [hlxsites/zemax#193]
https://main--zemax--hlxsites.hlx.page/pages/applications#imaging-optics
![image](https://github.com/hlxsites/zemax/assets/135161268/f67dfe37-4816-4e18-a434-23acd5d82905)
1. Move the title (Applications) over to be aligned with the the section underneath (imaging optics)
2. Font is too big and needs to be shrunken to fit the current zemax.com design
3. The title and button both need to be put within the grey the box

**Comment by Anthony-Hopkins-star** [comment]
[ Mobile ] 
**When clicking on collapsed set of content, the page should adjust its positioning and slide to the new open section rather then opening up and requiring the user to slide and view the new open content **

![image](https://github.com/hlxsites/zemax/assets/135161268/68de19dd-9a3e-453f-8136-6379cf68d088)
1. The title needs to be centered
2. The heading needs to smaller and closer and have less padding between the body text. The body text also needs to be smaller.

![image](https://github.com/hlxsites/zemax/assets/135161268/9b39c97c-8ee9-40f5-bf75-79fd6e4999e1)
1. Icons and text need to be left aligned and more compressed to look like the image that is presented below:
![image](https://github.com/hlxsites/zemax/assets/135161268/0490fdd3-60fa-49f7-a6cd-d99e0e285d07)
![image](https://github.com/hlxsites/zemax/assets/135161268/049b92e9-47f6-407e-b297-3b6d76e9aeac)
1. "View details" button needs to be put in the grey container.

**Comment by Anthony-Hopkins-star** [comment]
![image](https://github.com/hlxsites/zemax/assets/135161268/b13aa34b-d883-4994-bdb7-c58fe7e28a85)
1. The heading needs to smaller and closer and have less padding between the body text. The body text also needs to be smaller.
2. The text and image need to switch places (while in desktop mode)

**Comment by kunwarsaluja** [comment]
@synox can you take care of this ? Akshay isnt working on Zemax this week.

**Comment by synox** [comment]
@kunwarsaluja I can check it tomorrow
