### ISSUE TITLE
Mobile Navigation - Expanding the second level folds the entire section

### ISSUE THREAD

**Issue by kmurugulla** [hlxsites/zemax#201]

**Comment by kmurugulla** [comment]
Also - fixing the teaser close functionality

**Comment by synox** [comment]
@kmurugulla can you please show with a screenshot what needs to be changed?

**Comment by kmurugulla** [comment]
@synox 

![image](https://github.com/hlxsites/zemax/assets/7944122/aef32d76-2c3c-4090-a0d2-58bff7f44093)

Reference from zemax.com

![image](https://github.com/hlxsites/zemax/assets/7944122/b2049486-9f6b-4418-b9d0-7b848a803ffc)
