### ISSUE TITLE
Profile: on first login, window reloads forever

### ISSUE THREAD

**Issue by synox** [hlxsites/zemax#211]
Reproduce: Access http://localhost:3000/pages/profile with empty local storage and no cookies in Firefox. 

Because of https://github.com/hlxsites/zemax/pull/206, now the header does not wait until the access token is written into the local storage. 
Then when the zemax profile api is called, the token is still null.

**Comment by kmurugulla** [comment]
@synox - could you please take a quick look at lint issues and any conflicts so that we can merge this PR ?
