### ISSUE TITLE
Login Redirect

### ISSUE THREAD

**Issue by Anthony-Hopkins-star** [hlxsites/zemax#220]
After logging in, the user should be redirected back to the profile page.

**Comment by kunwarsaluja** [comment]
@synox with your latest changes, should this have been fixed already ?

**Comment by kunwarsaluja** [comment]
@synox  I don't see the redirect happening to the /pages/profile after login in the main branch like it's happening in the zemax live site(zemax.com).

**Comment by synox** [comment]
@kunwarsaluja Ah, I only fixed it for the case where you initiate it from https://main--zemax--hlxsites.hlx.page/pages/profile. 

Changing https://github.com/hlxsites/zemax/blob/25899093da400365bb82abf9e7edaa2245e95a92/blocks/header/header.js#L270-L274 to always return the profile url should fix it.
