### ISSUE TITLE
[Homepage] Optical Design Section

### ISSUE THREAD

**Issue by kmurugulla** [hlxsites/zemax#47]
Style Optical Design Section with Cloumns ( icons ) with section metadata to add orange color scheme for icons and links

![Screenshot 2023-04-11 at 12 35 57 PM](https://user-images.githubusercontent.com/7944122/231271384-abb13ccd-f3ff-475c-bf75-d884573ae7c8.png)

**Comment by agangam** [comment]
Ready for review : https://github.com/hlxsites/zemax/pull/91

**Comment by kmurugulla** [comment]
Reopening to optimize the CSS styles
