### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by kmurugulla** [hlxsites/zemax#6]
<img width="100" alt="image" src="https://user-images.githubusercontent.com/7944122/227586770-afa2998c-eaa1-4105-a03d-48d99029d95f.png">

**Comment by VladJav** [comment]
I can work on this issue, but can you provide a URL to download the favicon image you want?

**Comment by Divyanshu975** [comment]
Hey I would also like to work on this issue so could you please assign it to me
