### ISSUE TITLE
[Blogs] - Social navtool(sticky) for all pages under /blogs/news

### ISSUE THREAD

**Issue by kunwarsaluja** [hlxsites/zemax#61]
[Blogs] - Social navtool(sticky) for all pages under /blogs/news

See https://www.zemax.com/blogs/news/angus-macleod-in-memorium

All Blogs news can be identified as below (page metadata applied to all pages under /blog/news/ ): 
- meta name="template" content=blog-news>
- body class=blog-news>

**Mobile**
![Screenshot 2023-04-14 at 9 35 59 AM](https://user-images.githubusercontent.com/10811320/232058649-ebf7fb4e-6910-415f-89f7-ccdb839813e7.png)

**Tablet/Desktop**
![Screenshot 2023-04-13 at 4 17 56 PM](https://user-images.githubusercontent.com/10811320/231873544-23524168-064f-449a-bae4-13fefd78eb45.png)

**Comment by kmurugulla** [comment]
The name of this block should be - **social-share**
