### ISSUE TITLE
[Home Page] Styling and Aligning all sections

### ISSUE THREAD

**Issue by kmurugulla** [hlxsites/zemax#68]
- [ ] Styling of the background for sections
- [ ] Styling Default Content of sections
- [ ] Alignment of sections as it is in zemax.com

See below for comparison ( **Right** - Franklin , **Left** - Live Site )

**Header** (@kmurugulla )

![image](https://user-images.githubusercontent.com/7944122/232074034-aede65f6-bb48-4f40-96ab-8d86b0ea19f5.png)

- Header is not sticky
![Screenshot 2023-04-14 at 11 59 29 AM](https://user-images.githubusercontent.com/10811320/232095702-7e1ea442-bb70-41d0-9b48-790e0729f3df.png)

---

**Teaser** (@agangam )

![image](https://user-images.githubusercontent.com/7944122/232074236-b6230f39-6c13-41c6-8a83-efd7321f9f2f.png)

---

**Hero** (@kunwarsaluja )

![image](https://user-images.githubusercontent.com/7944122/232074361-80699cee-915e-42a9-89d6-d64460842fef.png)

---

**Trusted By Section** (@kmurugulla )

![image](https://user-images.githubusercontent.com/7944122/232074560-250093ec-2cf6-4122-955f-b0303d4bc676.png)

---

**Design for Manufacturability** (@kmurugulla )

![image](https://user-images.githubusercontent.com/7944122/232074722-e7642d43-1cf8-412b-9df3-950a260796a8.png)

---

**Zemax Software Section** (@FrancoisZhang )

![image](https://user-images.githubusercontent.com/7944122/232075012-b549f1fd-9702-44e0-ab54-f378512e7141.png)

---

**Customer Success Stories** (@FrancoisZhang )

![image](https://user-images.githubusercontent.com/7944122/232075268-a6d61ae9-e0e9-4873-aa63-62c6c81198b1.png)

---

**Training Section** (@FrancoisZhang )

![image](https://user-images.githubusercontent.com/7944122/232075500-cf1cccca-9add-4d49-a7eb-b27e5d013ec8.png)

---

**Subscribe to Blog Section** (@kunwarsaluja )

![image](https://user-images.githubusercontent.com/7944122/232076152-417a54ec-cb82-4762-b192-3d025f850a20.png)

---

**Footer** (@kunwarsaluja )

![image](https://user-images.githubusercontent.com/7944122/232076382-acfdf892-fe3c-4507-ab71-8f736c694685.png)

**Comment by kunwarsaluja** [comment]
Closing this for now..will reopen new issue when we start QA cycle
