### ISSUE TITLE
[Homepage] Build Trusted by Carousel 

### ISSUE THREAD

**Issue by kmurugulla** [hlxsites/zemax#7]
- [ ] Mobile
- [ ] Tablet
- [ ] Desktop
- [ ] Update Block [Library](https://main--zemax--hlxsites.hlx.page/block-library/how-to-block-library)

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/7944122/227587275-0e6412b3-3b35-4b06-b2c2-faee69eca949.png">

**Comment by FrancoisZhang** [comment]
https://github.com/hlxsites/zemax/pull/35

**Comment by FrancoisZhang** [comment]
finished in PR: https://github.com/hlxsites/zemax/pull/65
