### ISSUE TITLE
[Product Landing Page] Hero Block

### ISSUE THREAD

**Issue by kmurugulla** [hlxsites/zemax#76]
The hero block on zemax.com is visually different from Product Landing Pages , so develop the Hero block for Product Landing Pages

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/7944122/232319564-cae40901-5d07-4787-bb0e-bdb634bebf4a.png">

**Comment by agangam** [comment]
@kmurugulla The links from our site are taking us to zemax.com, should I change that or is that covered in a different ticket ?

**Comment by kunwarsaluja** [comment]
This should be complete now with https://github.com/hlxsites/zemax/pull/141 & https://github.com/hlxsites/zemax/pull/142
