### ISSUE TITLE
[Product Landing Page] Trial Request Form Block for Trial pages

### ISSUE THREAD

**Issue by kmurugulla** [hlxsites/zemax#78]
Develop or create an existing block variant for Trail Request Form

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/7944122/232319824-f622a819-b141-40bc-97a9-8f8a2bfc7319.png">

**Comment by kunwarsaluja** [comment]
@kmurugulla This is already done, just need to curate the pages with the marketi block

ill take this one

**Comment by kunwarsaluja** [comment]
Done with content changes and marketo block additions : 
- https://main--zemax--hlxsites.hlx.page/pages/try-opticstudio-for-free
- https://main--zemax--hlxsites.hlx.page/pages/try-opticsbuilder-for-free
