### ISSUE TITLE
[Product Landing Page] Resource Center Cards Block

### ISSUE THREAD

**Issue by kmurugulla** [hlxsites/zemax#79]
Develop Resource Center Block , style it for all break points

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/7944122/232320191-f216ba13-d101-4b3a-8801-07e2565a1c2d.png">

**Comment by kunwarsaluja** [comment]
already completed via Cards block (resource-center theme). See block-library for card variations

https://main--zemax--hlxsites.hlx.page/block-library/blocks/cards
