### ISSUE TITLE
[Product Landing Page] Style Contact Us Page Layout

### ISSUE THREAD

**Issue by kmurugulla** [hlxsites/zemax#80]
The Contact Us Form and page layout 

https://www.zemax.com/pages/contact-us

<img width="865" alt="image" src="https://user-images.githubusercontent.com/7944122/232320408-dc57b4a6-1f0f-4fbb-a167-640e1fb8739b.png">

<img width="976" alt="image" src="https://user-images.githubusercontent.com/7944122/232320373-6b62ecbb-8bda-4af4-9378-a8d786a40a65.png">

**Comment by kunwarsaluja** [comment]
This is already done. Tiny styling changes might be required

**Comment by kunwarsaluja** [comment]
Please check https://main--zemax--hlxsites.hlx.page/pages/contact-us

before you start, please check **[this](https://github.com/hlxsites/zemax/blob/main/styles/styles.css#L683)** as these styles have to go away as they are overriding the global/scection styles.

**Comment by kunwarsaluja** [comment]
This is not needed anymore as they are redirecting to ansys contactus page.
